# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/patient_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19rpc/patient_service.proto\x12\x07patient\"\x99\x01\n\x07Patient\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x16\n\x0e\x62lood_pressure\x18\x04 \x01(\t\x12\x16\n\x0e\x64iabetes_level\x18\x05 \x01(\x02\x12\x13\n\x0b\x62lood_group\x18\x06 \x01(\t\x12\x0e\n\x06height\x18\x07 \x01(\x02\x12\x0e\n\x06weight\x18\x08 \x01(\x02\"\x07\n\x05\x45mpty\"\x18\n\x02Id\x12\x12\n\npatient_id\x18\x01 \x01(\x05\"F\n\rPatientWithId\x12\x12\n\npatient_id\x18\x01 \x01(\x05\x12!\n\x07patient\x18\x02 \x01(\x0b\x32\x10.patient.Patient2\xeb\x01\n\x0ePatientService\x12\x31\n\x0b\x61\x64\x64_patient\x12\x10.patient.Patient\x1a\x10.patient.Patient\x12\x36\n\x10get_all_patients\x12\x0e.patient.Empty\x1a\x10.patient.Patient0\x01\x12\x32\n\x11get_patient_by_id\x12\x0b.patient.Id\x1a\x10.patient.Patient\x12:\n\x0eupdate_patient\x12\x16.patient.PatientWithId\x1a\x10.patient.Patientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.patient_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PATIENT']._serialized_start=39
  _globals['_PATIENT']._serialized_end=192
  _globals['_EMPTY']._serialized_start=194
  _globals['_EMPTY']._serialized_end=201
  _globals['_ID']._serialized_start=203
  _globals['_ID']._serialized_end=227
  _globals['_PATIENTWITHID']._serialized_start=229
  _globals['_PATIENTWITHID']._serialized_end=299
  _globals['_PATIENTSERVICE']._serialized_start=302
  _globals['_PATIENTSERVICE']._serialized_end=537
# @@protoc_insertion_point(module_scope)
